name: Pull Request Test Handler

on:
  repository_dispatch:
    types:
      - test-command

env:
  AWS_DEFAULT_REGION: us-east-2

jobs:
  active_active_rhel7_proxy:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/aws-tests.yml@ah/tf-8609-fdo-6
    secrets: inherit
    name: Test AWS Active/Active RHEL7 Proxy Scenario
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'active-active-rhel7-proxy' }}
    with:
      test_name: Active/Active RHEL7 Proxy
      utility_test: false
      is_replicated_deployment: false
      module_repository_id: hashicorp/terraform-aws-terraform-enterprise
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      work_dir: ./tests/active-active-rhel7-proxy
      TFC_token_secret_name: ACTIVE_ACTIVE_RHEL7_PROXY_TFC_TOKEN
      TFC_workspace_substitution_pattern: 's/terraform {/terraform {\n\
        backend "remote" {\n\
          organization = "terraform-enterprise-modules-test"\n\
          workspaces {\n\
            name = "aws-active-active-rhel7-proxy"\n\
          }\n\
        }\n/'

  public_active_active:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/aws-tests.yml@ah/tf-8609-fdo-6
    secrets: inherit
    name: Test AWS Public Active/Active Scenario
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'public-active-active' }}
    with:
      test_name: Public Active/Active
      utility_test: false
      is_replicated_deployment: false
      module_repository_id: hashicorp/terraform-aws-terraform-enterprise
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      work_dir: ./tests/public-active-active
      TFC_token_secret_name: PUBLIC_ACTIVE_ACTIVE_TFC_TOKEN

  private_active_active:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/aws-tests.yml@ah/tf-8609-fdo-6
    secrets: inherit
    name: Test AWS Private Active/Active Scenario
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'private-active-active' }}
    with:
      test_name: Private Active/Active
      utility_test: false
      is_replicated_deployment: false
      module_repository_id: hashicorp/terraform-aws-terraform-enterprise
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      ssh_private_key_secret_name: PRIVATE_ACTIVE_ACTIVE_SSH_KEY_BASE64
      work_dir: ./tests/private-active-active
      TFC_token_secret_name: PRIVATE_ACTIVE_ACTIVE_TFC_TOKEN
      aws_access_key_id: PRIVATE_ACTIVE_ACTIVE_AWS_ACCESS_KEY_ID
      aws_secret_access_key: PRIVATE_ACTIVE_ACTIVE_AWS_SECRET_ACCESS_KEY
      aws_role_to_assume: PRIVATE_ACTIVE_ACTIVE_AWS_ROLE_TO_ASSUME

  private_tcp_active_active:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/aws-tests.yml@ah/tf-8609-fdo-6
    secrets: inherit
    name: Test AWS Private TCP Active/Active Scenario
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'private-tcp-active-active' }}
    with:
      test_name: Private TCP Active/Active
      utility_test: false
      is_replicated_deployment: false
      module_repository_id: hashicorp/terraform-aws-terraform-enterprise
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      ssh_private_key_secret_name: PRIVATE_TCP_ACTIVE_ACTIVE_SSH_KEY_BASE64
      work_dir: ./tests/private-tcp-active-active
      TFC_token_secret_name: PRIVATE_TCP_ACTIVE_ACTIVE_TFC_TOKEN
      aws_access_key_id: PRIVATE_TCP_ACTIVE_ACTIVE_AWS_ACCESS_KEY_ID
      aws_secret_access_key: PRIVATE_TCP_ACTIVE_ACTIVE_AWS_SECRET_ACCESS_KEY
      aws_role_to_assume: PRIVATE_TCP_ACTIVE_ACTIVE_AWS_ROLE_TO_ASSUME

  standalone_vault:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/aws-tests.yml@ah/tf-8609-fdo-6
    secrets: inherit
    name: Test AWS Standalone Vault Scenario
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'standalone-vault' }}
    with:
      test_name: Standalone Vault
      utility_test: false
      is_replicated_deployment: false
      module_repository_id: hashicorp/terraform-aws-terraform-enterprise
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      work_dir: ./tests/standalone-vault
      first_apply_args: "-target=module.hcp_vault.hcp_vault_cluster.test -target=module.hcp_vault.hcp_vault_cluster_admin_token.test"
      TFC_token_secret_name: STANDALONE_VAULT_TFC_TOKEN
      TFC_workspace_substitution_pattern: 's/terraform {/terraform {\n\
        backend "remote" {\n\
          organization = "terraform-enterprise-modules-test"\n\
          workspaces {\n\
            name = "aws-standalone-vault"\n\
          }\n\
        }\n/'

  active_active_rhel7_proxy_replicated:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/aws-tests.yml@ah/tf-8609-fdo-6
    secrets: inherit
    name: Test AWS Active/Active RHEL7 Proxy (Replicated) Scenario
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'active-active-rhel7-proxy-replicated' }}
    with:
      test_name: Active/Active RHEL7 Proxy (Replicated)
      utility_test: false
      is_replicated_deployment: true
      module_repository_id: hashicorp/terraform-aws-terraform-enterprise
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      work_dir: ./tests/active-active-rhel7-proxy
      TFC_token_secret_name: ACTIVE_ACTIVE_RHEL7_PROXY_REPLICATED_TFC_TOKEN
      TFC_workspace_substitution_pattern: 's/terraform {/terraform {\n\
        backend "remote" {\n\
          organization = "terraform-enterprise-modules-test"\n\
          workspaces {\n\
            name = "aws-active-active-rhel7-proxy-replicated"\n\
          }\n\
        }\n/'

  public_active_active_replicated:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/aws-tests.yml@ah/tf-8609-fdo-6
    secrets: inherit
    name: Test AWS Public Active/Active (Replicated) Scenario
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'public-active-active-replicated' }}
    with:
      test_name: Public Active/Active (Replicated)
      utility_test: false
      is_replicated_deployment: true
      module_repository_id: hashicorp/terraform-aws-terraform-enterprise
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      work_dir: ./tests/public-active-active
      TFC_token_secret_name: PUBLIC_ACTIVE_ACTIVE_REPLICATED_TFC_TOKEN
      TFC_workspace_substitution_pattern: s/aws-public-active-active/aws-public-active-active-replicated/

  private_active_active_replicated:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/aws-tests.yml@ah/tf-8609-fdo-6
    secrets: inherit
    name: Test AWS Private Active/Active (Replicated) Scenario
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'private-active-active-replicated' }}
    with:
      test_name: Private Active/Active (Replicated)
      utility_test: false
      is_replicated_deployment: true
      module_repository_id: hashicorp/terraform-aws-terraform-enterprise
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      ssh_private_key_secret_name: PRIVATE_ACTIVE_ACTIVE_SSH_KEY_BASE64
      work_dir: ./tests/private-active-active
      TFC_token_secret_name: PRIVATE_ACTIVE_ACTIVE_REPLICATED_TFC_TOKEN
      TFC_workspace_substitution_pattern: s/aws-private-active-active/aws-private-active-active-replicated/
      aws_access_key_id: PRIVATE_ACTIVE_ACTIVE_AWS_ACCESS_KEY_ID
      aws_secret_access_key: PRIVATE_ACTIVE_ACTIVE_AWS_SECRET_ACCESS_KEY
      aws_role_to_assume: PRIVATE_ACTIVE_ACTIVE_AWS_ROLE_TO_ASSUME

  private_tcp_active_active_replicated:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/aws-tests.yml@ah/tf-8609-fdo-6
    secrets: inherit
    name: Test AWS Private TCP Active/Active (Replicated) Scenario
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'private-tcp-active-active-replicated' }}
    with:
      test_name: Private TCP Active/Active (Replicated)
      utility_test: false
      is_replicated_deployment: true
      module_repository_id: hashicorp/terraform-aws-terraform-enterprise
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      ssh_private_key_secret_name: PRIVATE_TCP_ACTIVE_ACTIVE_SSH_KEY_BASE64
      work_dir: ./tests/private-tcp-active-active
      TFC_token_secret_name: PRIVATE_TCP_ACTIVE_ACTIVE_REPLICATED_TFC_TOKEN
      TFC_workspace_substitution_pattern: s/aws-private-tcp-active-active/aws-private-tcp-active-active-replicated/
      aws_access_key_id: PRIVATE_TCP_ACTIVE_ACTIVE_AWS_ACCESS_KEY_ID
      aws_secret_access_key: PRIVATE_TCP_ACTIVE_ACTIVE_AWS_SECRET_ACCESS_KEY
      aws_role_to_assume: PRIVATE_TCP_ACTIVE_ACTIVE_AWS_ROLE_TO_ASSUME

  standalone_vault_replicated:
    uses: hashicorp/terraform-random-tfe-utility/.github/workflows/aws-tests.yml@ah/tf-8609-fdo-6
    secrets: inherit
    name: Test AWS Standalone Vault (Replicated) Scenario
    if: ${{ github.event.client_payload.slash_command.args.unnamed.all == 'all' || github.event.client_payload.slash_command.args.unnamed.all == 'standalone-vault-replicated' }}
    with:
      test_name: Standalone Vault (Replicated)
      utility_test: false
      is_replicated_deployment: true
      module_repository_id: hashicorp/terraform-aws-terraform-enterprise
      k6_work_dir: ./tests/tfe-load-test
      pull_request_repo_name: ${{ github.event.client_payload.github.payload.repository.full_name }}
      pull_request_ref: ${{ github.event.client_payload.pull_request.head.sha }}
      pull_request_comment_id: ${{ github.event.client_payload.github.payload.comment.id }}
      work_dir: ./tests/standalone-vault
      first_apply_args: "-target=module.hcp_vault.hcp_vault_cluster.test -target=module.hcp_vault.hcp_vault_cluster_admin_token.test"
      TFC_token_secret_name: STANDALONE_VAULT_REPLICATED_TFC_TOKEN
      TFC_workspace_substitution_pattern: 's/terraform {/terraform {\n\
        backend "remote" {\n\
          organization = "terraform-enterprise-modules-test"\n\
          workspaces {\n\
            name = "aws-standalone-vault-replicated"\n\
          }\n\
        }\n/'
